include: package:lints/recommended.yaml

analyzer:
  errors:
    use_string_in_part_of_directives: ignore
    curly_braces_in_flow_control_structures: ignore
    unnecessary_library_name: ignore

linter:

  rules:
    - noop_primitive_operations
    - avoid_types_on_closure_parameters
    - prefer_int_literals
    - prefer_expression_function_bodies
    - unnecessary_breaks
    - avoid_annotating_with_dynamic
    - avoid_returning_this
    - one_member_abstracts
