name: stagexl_spine
version: 0.11.0
description: The Spine runtime for the StageXL library.
homepage: https://github.com/bp74/StageXL_Spine
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  stagexl:
    git: https://github.com/mnordine/StageXL.git

dev_dependencies:
  web: ^1.1.0
  lints: any
  build_test: any
  build_runner: any
  build_web_compilers: any
