name: stagexl_spine
version: 0.11.0
description: The Spine runtime for the StageXL library.
homepage: https://github.com/bp74/StageXL_Spine

environment:
  sdk: ^3.0.0

dependencies:
  stagexl: '>=2.0.0 <3.0.0'

dev_dependencies:
  lints: any
  build_test: any
  build_runner: any
  build_web_compilers: any
