name: stagexl_spine
version: 0.10.2
author: Bernhard Pichler <support@stagexl.org>
description: The Spine runtime for the StageXL library.
homepage: https://github.com/bp74/StageXL_Spine

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  stagexl:
    git:
      url: https://github.com/mnordine/StageXL
      ref: dart-2

dev_dependencies:
  pedantic: any
  build_test: any
  build_runner: any
  build_web_compilers: any
